# Generated by Django 3.0.5 on 2020-04-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(default='default_cover.png', upload_to='song/cover/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(upload_to='song/file/'),
        ),
    ]
