# Generated by Django 3.0.5 on 2020-04-20 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('song', '0002_auto_20200420_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.CharField(default='hrlll', max_length=64),
        ),
        migrations.AddField(
            model_name='song',
            name='user_likes',
            field=models.ManyToManyField(blank=True, related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('cover_image', models.ImageField(default='default_cover.png', upload_to='playlist/cover/')),
                ('slug', models.CharField(default='hrlll', max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('songs', models.ManyToManyField(related_name='songs', to='song.Song')),
            ],
        ),
    ]
