# Generated by Django 3.0.5 on 2020-04-20 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20200420_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.CharField(default='hrlll', max_length=64, unique_for_date='published'),
        ),
        migrations.AlterField(
            model_name='song',
            name='published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.CharField(default='hrlll', max_length=64, unique_for_date='published'),
        ),
    ]
