# Generated by Django 3.0.5 on 2020-04-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_auto_20200420_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.CharField(max_length=250, unique_for_date='published'),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.CharField(max_length=250, unique_for_date='published'),
        ),
    ]
