# Generated by Django 3.0.5 on 2020-04-22 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_auto_20200420_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-published']},
        ),
    ]
